Description: >
  Onoh Somtochukwu / Project 2 IAM / Udacity Nano Degree

Parameters:
  EnvironmentName:
    Description: Will be prefixed to all resources names
    Type: String

Resources:
  IAMWebApp:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
  WebAppPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${EnvironmentName}-WebApp-Policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource:
              !Join [
                "",
                [
                  "arn:aws:s3:::",
                  Fn::ImportValue: !Sub "${EnvironmentName}-BucketData",
                  /*,
                ],
              ]
      Roles:
        - !Ref IAMWebApp

  WebAppProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - !Ref IAMWebApp
Outputs:
  InstanceProfile:
    Description: Profile Instance for the web app server to access s3 bucket
    Value: !Ref WebAppProfile
    Export:
      Name: !Sub "${EnvironmentName}-Profile"
